# Use root/example as user/password credentials
# docker-compose up
version: '3.1'

services:
    adminer:
      image: adminer
      restart: always
      ports:
        - 8099:8080

    db:
      image: mysql:5.6
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: db_data_123
      ports:
        - 3307:3306

    php72_apache:
      build:
        context: ./.docker
      volumes:
        - .apache/:/etc/apache2/v-host/
        - ./www:/var/www
      ports:
        - 8030:80
